version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: appcenter-prometheus
    ports:
      - "9095:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
    networks:
      - monitoring
      - gravit-prod
      - gravit-dev

  grafana:
    image: grafana/grafana:latest
    container_name: appcenter-grafana
    ports:
      - "3030:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://monitoring.inuappcenter.kr
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
  gravit-prod:
    external: true
    name: prod_gravit-prod
  gravit-dev:
    external: true
    name: dev_gravit-dev

volumes:
  prometheus-data:
  grafana-data: