apiVersion: 1

# 프로메테우스
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://appcenter-prometheus:9090
    isDefault: true
    editable: true

  - name: Loki-intip
    type: loki
    access: proxy
    url: http://intip-loki:3100
    editable: true
